GET {{url}}/auth/test

###
POST {{url}}/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"

}

###

POST {{url}}/auth/login

{

"username": "admin",
"password": "admin123"

}

> {%
    client.global.set("jwt_token", response.body.token);

%}

###




### Get all trips
GET {{url}}/trips/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get trip by ID
GET {{url}}/trips/2
Accept: application/json
Authorization: Bearer {{jwt_token}}


### Create a new trip
POST {{url}}/trips/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "New Trip",
  "price": 5000,
  "category": "CITY",
  "startTime": "2025-06-01",
  "endTime": "2025-06-10",
  "startPosition": "New York"
}

### Update a trip by ID
PUT {{url}}/trips/10
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Updated Trip",
  "price": 6000,
  "category": "CITY",
  "startTime": "2025-06-01",
  "endTime": "2025-06-10",
  "startPosition": "New York"
}

### Add a guide to a trip
PUT {{url}}/trips/trips/10/guides/3
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Delete a trip by ID
DELETE {{url}}/trips/10
Authorization: Bearer {{jwt_token}}

### Get trips by guide ID
GET {{url}}/trips/guides/3
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get trips by category
GET {{url}}/trips/category/CITY
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get trips by price range
GET {{url}}/trips/guides/totalprice/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

